# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
default_language_version:
  python: python3.9.17
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args:
          - '--markdown-linebreak-ext=md'
      - id: check-case-conflict
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-xml
      - id: check-json
        exclude: .vscode
      - id: debug-statements
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      - id: detect-private-key
      - id: pretty-format-json
        exclude: .vscode
        args:
          - '--autofix'
#  - repo: https://github.com/dhruvmanila/remove-print-statements
#    rev: 'v0.5.1'
#    hooks:
#      - id: remove-print-statements
  - repo: 'https://github.com/PyCQA/autoflake'
    rev: v2.1.1
    hooks:
      - id: autoflake
        files: \.(py)$
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: "v0.3.1"
    hooks:
      - id: absolufy-imports
  #- repo: 'https://github.com/psf/black'
  #  rev: 23.3.0
  #  hooks:
  #    - id: black
  #      exclude: ^examples/|^tests/
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        files: \.(py)$
        args: ["--profile", "black", "--line-length=100"]
        exclude: ^examples/|^tests/
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.2'
    hooks:
      - id: autopep8
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 6.0.0
    hooks:
      - id: flake8
        files: \.(py)$
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ "-x", "tests" ]
        exclude: ^examples/|^tests/

  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: env PYTHONPATH=${PYTHONPATH}:./src/:./tests python3 -m unittest discover ./tests
        language: system
        'types': [ python ]
        pass_filenames: false
        stages: [ commit ]