name_target = "target"

var_drop = [
    "amount",
    "first_payment_date",
    "minfraud_modified_on",
    "emailage_modified_on",
    "customer_id",
    "document_id",
    "emailage_response__emailAge",
    "emailage_response__userdefinedrecordid",
    "emailage_response__eName",
    "emailage_response__domainAge",
    "emailage_response__ipaddress",
    "emailage_response__EAReasonID",
    "emailage_response__EAAdviceID",
    "emailage_response__EARiskBand",
    "emailage_response__lastflaggedon",
    "emailage_response__dob",
    "emailage_response__location",
    "emailage_response__imageurl",
    "emailage_response__domaincompany",
    "emailage_response__domaincountryname",
    "emailage_response__domainrelevantinfo",
    "emailage_response__domaincountrymatch",
    "emailage_response__ip_proxydescription",
    "emailage_response__ip_continentCode",
    "emailage_response__email",
    "emailage_response__country",
    "emailage_response__EAReason",
    "emailage_response__ip_riskreason",
    "emailage_response__ip_riskreasonid",
    "emailage_response__ip_risklevel",
    "minfraud_response__warnings__0__warning",
    "minfraud_response__ip_address__country__is_high_risk",
    "minfraud_response__ip_address__country__is_in_european_union",
    "minfraud_response__ip_address__country__geoname_id",
    "minfraud_response__ip_address__location__time_zone",
    "minfraud_response__ip_address__subdivisions__1__names__zh-CN",
    "minfraud_response__ip_address__risk_reasons__1__reason",
    "minfraud_response__ip_address__risk",
    "minfraud_response__ip_address__registered_country__iso_code",
    "minfraud_response__ip_address__registered_country__geoname_id",
    "minfraud_response__ip_address__subdivisions__0__confidence",
    "minfraud_response__ip_address__subdivisions__0__iso_code",
    "minfraud_response__ip_address__subdivisions__0__geoname_id",
    "minfraud_response__ip_address__subdivisions__1__iso_code",
    "minfraud_response__ip_address__subdivisions__1__geoname_id",
    "minfraud_response__ip_address__traits__static_ip_score",
    "minfraud_response__ip_address__continent__geoname_id",
    "minfraud_response__ip_address__postal__confidence",
    "minfraud_response__ip_address__postal__code",
    "minfraud_response__billing_address__latitude",
    "minfraud_response__billing_address__longitude",
    "minfraud_response__billing_address__distance_to_ip_location",
    "minfraud_response__id",
    "minfraud_response_time",
    "minfraud_response__ip_address__traits__mobile_country_code",
    "minfraud_response__ip_address__risk_reasons__1__code",
    "minfraud_response__ip_address__traits__ip_address",
    "minfraud_response__traits__ip_address__network",
    "minfraud_response__shipping_address__latitude",
    "minfraud_response__shipping_address__longitude",
    "minfraud_response__shipping_address__distance_to_ip_location",
    "minfraud_response__shipping_address__distance_to_billing_address",
    "minfraud_response__shipping_address__is_high_risk",
    "minfraud_response__ip_address__traits__is_hosting_provider",
    "minfraud_response__funds_remaining",
    "emailage_response__ip_latitude",
    "emailage_response__ip_longitude",
    "emailage_response_time",
    "emailage_response__ip_countryconf",
    "emailage_response__ip_map",
    "emailage_response__ipriskcountry",
    "emailage_response__ipdistancekm",
    "emailage_response__ipdistancemil",
    "emailage_response__ipaccuracyradius",
    "emailage_response__ip_riskscore",
    "emailage_response__smlinks__0__link",
    "emailage_response__smlinks__1__link",
    "emailage_response__smlinks__2__link",
    "emailage_response__smlinks__3__link",
    "emailage_response__smlinks__4__link",
    "emailage_response__custphoneInbillingloc",
    "emailage_response__citypostalmatch",
    "emailage_response__shipcitypostalmatch",
    "emailage_response__billriskcountry",
    "emailage_response__phoneownermatch",
    "experian_ID_SUSCRIPTOR",
    "experian_FECHA_NACIMIENTO",
    "experian_@xmlns",
    "experian_REFERENCIA_CONSULTA",
    "experian_Documento__NumeroDocumento",
    "uuid_x",
    "iovation_device__browser__timezone"
]

# Created high risk industry
var_pending_analysis = [
    'emailage_response__source_industry',
    'emailage_response__totalhits',
    'emailage_response__uniquehits',
    'emailage_response__company',
    'emailage_response__title',
    'emailage_response__ip_proxytype',
    'emailage_response__ip_isp',
    'emailage_response__ip_org',
    'minfraud_response__ip_address__location__latitude',
    'minfraud_response__ip_address__location__longitude',
    'minfraud_response__ip_address__location__local_time',
    'minfraud_response__warnings__0__code',
    'minfraud_response__warnings__0__input_pointer',
    'minfraud_response__ip_address__country__confidence',
    'minfraud_response__ip_address__country__iso_code',
    'minfraud_response__ip_address__location__accuracy_radius',
    'minfraud_response__ip_address__city__confidence',
    'minfraud_response__ip_address__city__geoname_id',
    'minfraud_response__queries_remaining',
    'minfraud_response__ip_address__traits__mobile_network_code',
    'minfraud_response__ip_address__traits__user_count',
    'minfraud_response__ip_address__risk_reasons__0__code',
    'minfraud_response__ip_address__risk_reasons__0__reason',
    'minfraud_response__ip_address__traits__autonomous_system_number',
    'minfraud_response__ip_address__traits__domain',
    'minfraud_response__ip_address__traits__autonomous_system_organization',
    'minfraud_response__ip_address__traits__isp',
    'minfraud_response__email__domain__first_seen',
    'minfraud_response__email__first_seen',
    'emailage_response__ip_country',
    'emailage_response__ip_countryCode',
    'emailage_response__ip_region',
    'emailage_response__ip_regionconf',
    'emailage_response__ip_city',
    'emailage_response__ip_callingcode',
    'emailage_response__ip_metroCode',
    'emailage_response__iptimezone',
    'emailage_response__ipasnum',
    'emailage_response__ipdomain',
    'emailage_response__ip_cityconf',
    'emailage_response__ip_postalcode',
    'emailage_response__ip_postalconf',
    'emailage_response__smlinks__0__source',
    'emailage_response__smlinks__1__source',
    'emailage_response__smlinks__2__source',
    'emailage_response__smlinks__3__source',
    'emailage_response__smlinks__4__source',
    'emailage_response__namematch',
    'emailage_response__phoneowner',
    'emailage_response__phoneownertype',
    'emailage_response__phonecarriertype',
    'emailage_response__phonecarriernetworkcode',
    'experian_Error__Codigo',
    'experian_Error__Descripcion',
    'experian_DIRECCION__Direccion',
    'experian_DIRECCION__NombreLocalidad',
    'experian_DIRECCION__Provincia__Codigo',
    'experian_DIRECCION__Provincia__Descripcion',
    'experian_DIRECCION__CodigoPostal',
    'experian_PRODUCTO_SOLICITADO',
    'experian_CANAL_SOLICITUD',
    'experian_Documento__PaisDocumento__Codigo',
    'experian_ResumenCais__FechaUltimaActualizacion',
    'experian_OrigenScore__Descripcion',
    'experian_Documento__PaisDocumento__Descripcion',
    'iovation_statedIp__ipLocation__city',
    'iovation_statedIp__ipLocation__country',
    'iovation_statedIp__ipLocation__countryCode',
    'iovation_statedIp__ipLocation__latitude',
    'iovation_statedIp__ipLocation__longitude',
    'iovation_statedIp__ipLocation__region',
    'iovation_realIp__ipLocation__city',
    'iovation_realIp__ipLocation__country',
    'iovation_realIp__ipLocation__countryCode',
    'iovation_realIp__ipLocation__latitude',
    'iovation_realIp__ipLocation__longitude',
    'iovation_realIp__ipLocation__region',
    'iovation_realIp__address',
    'iovation_statedIp__address',
    'iovation_device__browser__flash__installed',
    'iovation_device__browser__flash__version',
    'iovation_realIp__parentOrganization',
    'iovation_realIp__isp',
    'iovation_statedIp__parentOrganization',
    'iovation_statedIp__source',
    'iovation_statedIp__isp',
    'iovation_device__screen',
    'iovation_device__browser__version',
    'iovation_device__browser__language',
    'iovation_device__browser__configuredLanguage',
    'iovation_device__blackboxMetadata__timestamp',
    'iovation_device__alias',
    'iovation_device__firstSeen',
    'iovation_statedIp__botnet__lastSeen',
    'iovation_realIp__botnet__lastSeen'
]

delete_correlation = ['experian_InformacionDelphi__Decil',
                      'emailage_response__firstVerificationDate_difference_with_created',
                      'emailage_response__EAScore']

feature_importance = ['emailage_response__domainname',
                      'experian_ResumenCais__NumeroOperacionesImpagadas',
                      'principal', 'emailage_response__ip_risklevelid',
                      'experian_ResumenCais__MaximoImporteImpagado',
                      'experian_documento__tipodocumento__descripcion_trans',
                      'experian_InformacionDelphi__Puntuacion',
                      'experian_ResumenCais__NumeroCuotasImpagadas',
                      'experian_ResumenCais__ImporteImpagado',
                      'experian_InformacionDelphi__Decil', 'downpayment_amount',
                      'minfraud_response__risk_score',
                      'annual_percentage_rate', 'emailage_response__fraudRisk',
                      'n_initial_instalments', 'age',
                      'experian_InformacionDelphi__ProbabilidadIncumplimientoPorScore',
                      'emailage_response__domain_creation_days',
                      'minfraud_response__ip_address__continent__code_nan',
                      'emailage_response__phonecarriername',
                      'experian_InformacionDelphi__Percentil',
                      'minfraud_response__ip_address__traits__user_type_nan',
                      'emailage_response__first_seen_days',
                      'industry_id', 'emailage_response__EAAdvice', 'merchant_id',
                      'emailage_response__EAScore',
                      'emailage_response__domainrisklevel',
                      'minfraud_response__ip_address__traits__user_type_business',
                      'minfraud_response__ip_address__traits__user_type_hosting',
                      'order_uuid']

features_remove = ['iovation_device__browser__type_MAXBROWSER',
                   'emailage_response__domaincategory_Arts',
                   'emailage_response__domaincategory_Real Estate',
                   'emailage_response__domaincategory_Facilities Services',
                   'emailage_response__domaincategory_Internet Ecosystem Services',
                   'emailage_response__domaincategory_Online Information Management',
                   'emailage_response__domaincategory_Utility',
                   'emailage_response__ip_netSpeedCell_cable',
                   'emailage_response__ip_netSpeedCell_mobile',
                   'emailage_response__domaincategory_Tech0logy',
                   'emailage_response__domaincategory_Other',
                   'emailage_response__domaincategory_Technology, Businesses & Services (General)',
                   'emailage_response__domaincategory_Mail',
                   'emailage_response__ip_netSpeedCell_wireless',
                   'emailage_response__ip_netSpeedCell_t1',
                   'emailage_response__domaincategory_Construction ',
                   'emailage_response__domainrelevantinfoID_537.0',
                   'emailage_response__ip_netSpeedCell_satellite',
                   'emailage_response__ip_netSpeedCell_xdsl',
                   'emailage_response__domaincategory_Malware Distribution Point']
